#!/bin/sh
# palmar installer — one line, no build, no dependency to fetch.
#
#   curl -fsSL <url>/install.sh | sh          # the quick way
#   curl -fsSL <url>/install.sh -o install.sh # the careful way: read it first, then
#   sh install.sh
#
# **This does almost nothing on purpose.** palmar is the Python standard library and a vendored
# copy of xterm.js — there is no binary to download and nothing to compile. So this script only:
#   1. checks a Python new enough is already here (macOS ships /usr/bin/python3 3.9; most Linux has one)
#   2. puts palmar where `palmar` on the command line will find it
#   3. tells you the one command to run
#
# It never runs the daemon, never touches ~/.palmar, and never needs root. If any of it is not to
# your taste, `git clone` the repo and `python3 -m palmar` does the same thing with nothing installed.

set -eu

# ── where palmar comes from ────────────────────────────────────────────────────────────────
# Left as placeholders until the repo is public / on PyPI (the user's call). When either is set,
# this script fetches from there; run from inside a clone, it installs the checkout you are in.
PALMAR_PYPI="${PALMAR_PYPI:-}"          # e.g. "palmar" once uploaded — then pip/uv can be used
PALMAR_TARBALL="${PALMAR_TARBALL:-}"    # e.g. a github codeload .tar.gz once the repo is public
PREFIX="${PALMAR_PREFIX:-$HOME/.local}"

say()  { printf '%s\n' "$*"; }
warn() { printf '%s\n' "$*" >&2; }
die()  { printf 'install: %s\n' "$*" >&2; exit 1; }

# ── 1. a Python new enough ─────────────────────────────────────────────────────────────────
# 3.9 is the floor because that is what macOS ships (spike H). Find the first python that clears it.
find_python() {
  for py in python3 python3.13 python3.12 python3.11 python3.10 python3.9 python; do
    if command -v "$py" >/dev/null 2>&1 && \
       "$py" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3,9) else 1)' 2>/dev/null; then
      command -v "$py"
      return 0
    fi
  done
  return 1
}

PY="$(find_python || true)"
[ -n "$PY" ] || die "no Python 3.9 or newer found.
  palmar is pure Python and needs one to run. macOS has /usr/bin/python3 already;
  on Linux install python3 from your package manager, then run this again."
say "using $("$PY" --version 2>&1) at $PY"

# ── 2. get palmar onto disk ────────────────────────────────────────────────────────────────
# Three sources, in the order that needs the least from the machine. Only the first works today;
# the other two switch on the moment the repo is public or on PyPI.
SRC=""
if [ -f "$(unset CDPATH; cd -- "$(dirname -- "$0")" && pwd)/palmar/__init__.py" ]; then
  # Run from inside a checkout — install exactly this tree, no download.
  SRC="$(unset CDPATH; cd -- "$(dirname -- "$0")" && pwd)"
  say "installing from the checkout at $SRC"
elif [ -n "$PALMAR_PYPI" ]; then
  say "installing $PALMAR_PYPI from PyPI"
  "$PY" -m pip install --user --upgrade "$PALMAR_PYPI" || die "pip install failed"
  INSTALLED_VIA_PIP=1
elif [ -n "$PALMAR_TARBALL" ]; then
  TMP="$(mktemp -d)"
  trap 'rm -rf "$TMP"' EXIT
  say "downloading palmar"
  curl -fsSL "$PALMAR_TARBALL" -o "$TMP/palmar.tar.gz" || die "download failed"
  tar -xzf "$TMP/palmar.tar.gz" -C "$TMP"
  SRC="$(find "$TMP" -maxdepth 2 -name '__init__.py' -path '*/palmar/*' -exec dirname {} \; | head -1)"
  SRC="$(dirname "$SRC")"
  [ -f "$SRC/palmar/__init__.py" ] || die "the downloaded archive did not contain palmar/"
else
  die "no source to install from.
  Run this from inside a 'git clone' of palmar, or set PALMAR_PYPI / PALMAR_TARBALL.
  (The repository is private for now; a public one-line install is coming.)"
fi

# ── 3. make `palmar` runnable ──────────────────────────────────────────────────────────────
if [ "${INSTALLED_VIA_PIP:-}" = "1" ]; then
  BIN="$("$PY" -c 'import sysconfig,os;print(os.path.join(sysconfig.get_path("scripts",scheme="posix_user"),"palmar"))' 2>/dev/null || true)"
  say ""
  say "installed. run:  palmar"
  [ -x "$BIN" ] || warn "note: $BIN may not be on your PATH — add its directory if 'palmar' is not found"
else
  # No pip: drop a tiny shim that runs the tree in place. Nothing is copied, so a 'git pull' in the
  # checkout updates palmar with no reinstall — which is how the daemon already expects to live (⑦=b).
  mkdir -p "$PREFIX/bin"
  SHIM="$PREFIX/bin/palmar"
  # A launcher, not a copy. It points PYTHONPATH at the tree in place, so a `git pull` in the
  # checkout updates palmar with no reinstall — the daemon already expects to live that way (⑦=b).
  cat > "$SHIM" <<SHIM_EOF
#!/bin/sh
# Generated by palmar's install.sh. Runs the tree at the path below with the Python picked then.
exec env PYTHONPATH="$SRC\${PYTHONPATH:+:\$PYTHONPATH}" "$PY" -m palmar "\$@"
SHIM_EOF
  chmod +x "$SHIM"
  say ""
  say "installed a launcher at $SHIM"
  case ":$PATH:" in
    *":$PREFIX/bin:"*) say "run:  palmar" ;;
    *) say "add $PREFIX/bin to your PATH, then run:  palmar
  e.g.  echo 'export PATH=\"$PREFIX/bin:\$PATH\"' >> ~/.profile
  or just run it directly:  $SHIM" ;;
  esac
fi

say ""
say "palmar prints a URL on its last line — open that in a browser. Ctrl-C stops it."
